  repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: fix-encoding-pragma
      - id: check-illegal-windows-names
      - id: check-json
      - id: pretty-format-json
        args: ['--indent', '4']
      - id: check-yaml
      - id: sort-simple-yaml
        files: ^(?!.*(config\.yaml|settings\.yml)$).*\.ya?ml$
      - id: check-toml
      - id: check-xml
      - id: file-contents-sorter
        args: ['--ignore-case']
      - id: check-merge-conflict
        args: ['--assume-in-merge']
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: debug-statements
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: forbid-submodules
      - id: name-tests-test
        args: ['--pytest-test-first']
      - id: no-commit-to-branch
        args: ['main', 'master']
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3.13
