name: CI

on:
  push:
    branches: [*/*]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Install pre-commit and Commitizen
        run: |
          pip install pre-commit commitizen

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest
          coverage xml -o coverage_reports/coverage.xml
      
      - name: Run DeepSource analysis
        run: |
          curl -sSL https://deepsource.io/cli/install.sh | bash
          deepsource analyze
      
      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage_reports/coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
      
      - name: Bump version and create tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cz bump --yes
          
      - name: Generate CHANGELOG.md
        run: |
          cz changelog --yes
